### ISSUE TITLE
Box Colours

### ISSUE THREAD

**Issue by littlerob84** [NicoMandel/asdc_mwe#5]
Responding to:
_Box Colours Makes sense. Since this is a scaling based on single input value, we can modify this to be anything. e.g. different shading of blue, see [this line](https://github.com/NicoMandel/asdc_mwe/blob/6b500a5872cd0295c1649a29cd6602eea68a9464/visualise_bbox.py#L21). Just let me know what you need_

I think just one solid colour is best as shades might mean a lighter shades box gets missed? I used the following when I was testing confidence levels and these colours all stood out well in the terrain we are flying over. If possible:

- High confidence - Black
- Med confidence - Blue
- Low confidence - Yellow

If that's too hard, shading just blue will be fine.

**Comment by NicoMandel** [comment]
Hi Rob

I had a look and these are the RGB values for yellow blue and black: 
        yellow is (255, 255, 0)
        blue is (0, 0, 255)
        black is (0, 0, 0)
I do not see a linear scaling there between those three, so I'll just scale blue to be darker according to the confidence level.
Of course we can adapt this further if needs be.

**Comment by NicoMandel** [comment]
If you guys could figure out 3 box colours that I can scale between with a single input value, I'd be really happy.
So I get 1 input value, the confidence [here](https://github.com/NicoMandel/asdc_mwe/blob/6b500a5872cd0295c1649a29cd6602eea68a9464/visualise_bbox.py#L16) and all I have to do is scale the R channel down and the G channel up depending on the confidence to get a traffic light, while keeping the B channel constant. 
Now with your desired values and the corresponding RGB values:
High confidence (input value 1.0) - Blue - (0, 0, 255)
Medium confidence (input value 0.5)  - Yellow - (128, 128, 0) or (255, 255, 0) or (128, 128, 20)
Low confidence - black - (input value 0.0) - Black - (0,0,0)

It's really difficult for me to scale, because I have to change R, as well as G as well as B and none of them linearly.... If you can figure out a scheme that would allow me to scale without having to change nonlinearly (e.g. if conf goes up, everything should go either up or down... just not first up and then down)
You can basically choose from any colour space and I can construct the value and then convert it, it doesn't need to be RGB. The two most common ones are RGB and HSV (hue-saturation-value):
![rgbcube](https://github.com/NicoMandel/asdc_mwe/assets/48271729/faaccbac-b8f7-4184-a23a-c47924d61b98)
So I can scale linearly in that cube, or I can choose the HSV colour space and use that to construct colours:
![hsv](https://github.com/NicoMandel/asdc_mwe/assets/48271729/49da0786-d642-4e6a-a1cb-590e612fb4fb)

Worth sitting down for 10 minutes with pen and paper and looking at some colours, just let me know which ones you want.

**Comment by littlerob84** [comment]
I think as Blue is quite an easy colour to see in all the landscapes we capture, that should be the base colour, with full blue (0, 0, 255) the high confidence and then scaling the B channel down as the confidence goes down, so that 0,0,0 (which is black) is low confidence. That means only scaling the B channel down in a linear function based on the confidence level.

So high confidence = 0,0,255
Medium confidence = 0,0,127
Low confidence = 0,0,0

Need to confirm Mark is happy with this before committing to.
